version: '3'

services:
  postgres-db:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: banking
      POSTGRES_PASSWORD: postgres

  rabbitMq:
    image: "rabbitmq:3-management"
    hostname: "rabbitMq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

  banking-webapp:
    image: banking-system
    depends_on:
      - postgres-db
      - rabbitMq
    ports:
      - 8080:8080
    environment:
      DATABASE_HOST: postgres-db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: banking
      DATABASE_PORT: 5432
      RABBIT_MQ_HOST: rabbitMq
      RABBIT_MQ_USER: rabbitmq
      RABBIT_MQ_PASS: rabbitmq
      RABBIT_MQ_PORT: 5672

  logging-webapp:
    image: logging-system
    depends_on:
      - postgres-db
      - rabbitMq
    ports:
      - 8081:8081
    environment:
      DATABASE_HOST: postgres-db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: banking
      DATABASE_PORT: 5432
      RABBIT_MQ_HOST: rabbitMq
      RABBIT_MQ_USER: rabbitmq
      RABBIT_MQ_PASS: rabbitmq
      RABBIT_MQ_PORT: 5672


#    labels:
#      NAME: "rabbitmq1"
#    volumes:
#      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"


#  banking-mysql:
#    image: mysql:latest
#    environment:
#      - MYSQL_ROOT_PASSWORD=p4SSW0rd
#      - MYSQL_DATABASE=demo
#      - MYSQL_USER=dbuser
#      - MYSQL_PASSWORD=dbp4ss



#      - DATABASE_HOST=postgres-db
#      - DATABASE_USER=postgres
#      - DATABASE_PASSWORD=postgres
#      - DATABASE_NAME=banking
#      - DATABASE_PORT=5432
